In [28]:
import pandas as pd
from sklearn.metrics import confusion_matrix
import disarray
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [29]:
party_classifications = pd.read_pickle('../data/sentiment/party_sentiment_classifications.pkl')
politician_classifications = pd.read_pickle('../data/sentiment/politician_sentiment_classifications.pkl')
party_mentions = pd.read_pickle('../data/sentiment/party_mentions.pkl')
politician_mentions = pd.read_pickle('../data/sentiment/politician_mentions.pkl')
party_classifications_without_trump = party_classifications.loc[party_classifications['party'] != 'trump']

In [30]:
sent_sample_reemt = party_classifications_without_trump.sample(random_state=44, n=100).reset_index()
sent_sample_reemt.to_pickle('../data/plausibility_tests/reemt_sentiment_2.pkl')
sent_sample_reemt['extracted_string'].to_csv('../data/plausibility_tests/reemt_sentiment_2.csv')

In [31]:
sent_sample_hauke = party_classifications_without_trump.sample(random_state=45, n=100).reset_index()
sent_sample_hauke.to_pickle('../data/plausibility_tests/hauke_sentiment_2.pkl')
sent_sample_hauke['extracted_string'].to_csv('../data/plausibility_tests/hauke_sentiment_2.csv')

In [32]:
for party in ['linke', 'grüne', 'spd', 'fdp', 'cdu', 'csu', 'afd']:
    politician_sample_reemt = politician_classifications[politician_classifications['party'] == party].sample(random_state=46,n=50)
    party_sample_reemt = party_classifications[party_classifications['party'] == party].sample(random_state=47,n=50)
    politician_sample_hauke = politician_classifications[politician_classifications['party'] == party].sample(random_state=48,n=50)
    party_sample_hauke = party_classifications[party_classifications['party'] == party].sample(random_state=49,n=50)

    politician_sample_reemt.extracted_string.to_csv(f'../data/plausibility_tests/reemt_politician_{party}_2.csv')
    party_sample_reemt.extracted_string.to_csv(f'../data/plausibility_tests/reemt_party_{party}_2.csv')
    politician_sample_hauke.extracted_string.to_csv(f'../data/plausibility_tests/hauke_politician_{party}_2.csv')
    party_sample_hauke.extracted_string.to_csv(f'../data/plausibility_tests/hauke_party_{party}_2.csv')

    politician_sample_reemt.to_pickle(f'../data/plausibility_tests/reemt_politician_{party}_2.pkl')
    party_sample_reemt.to_pickle(f'../data/plausibility_tests/reemt_party_{party}_2.pkl')
    politician_sample_hauke.to_pickle(f'../data/plausibility_tests/hauke_politician_{party}_2.pkl')
    party_sample_hauke.to_pickle(f'../data/plausibility_tests/hauke_party_{party}_2.pkl')
    

In [33]:
test123 = sent_sample_hauke['extracted_string']

In [34]:
plausibility_test = [
    'neg',#0
    'neu',#1
    'neu',#2
    'neg',#3
    'neg',#4
    'pos',#5
    'pos',#6
    'pos',#7
    'neg',#8
    'neu',#9
    'pos',#10
    'neu',#11
    'pos',#12
    'neg',#13
    'neu',#14
    'neg',#15
    'neg',#16
    'neu',#17
    'neu',#18
    'neg',#19
    'neu',#20
    'neu',#21
    'neg',#22
    'pos',#23
    'neg',#24
    'neg',#25
    'pos',#26
    'neu',#27
    'neu',#28
    'neu',#29
    'neg',#30
    'neg',#31
    'neg',#32
    'neu',#33
    'neu',#34
    'neg',#35
    'neu',#36
    'neu',#37
    'neu',#38
    'neu',#39
    'neg',#40
    'neg',#41
    'neg',#42
    'neg',#43
    'neu',#44
    'neu',#45
    'neu',#46
    'neu',#47
    'neg',#48
    'neg',#49
    'neu',#50
    'neu',#51
    'neu',#52
    'pos',#53
    'neg',#54
    'neu',#55
    'neg',#56
    'neu',#57
    'neu',#58
    'neu',#59
    'neu',#60
    'neu',#61
    'neg',#62
    'pos',#63
    'neu',#64
    'neg',#65
    'neu',#66
    'pos',#67
    'neg',#68
    'pos',#69
    'neu',#70
    'neg',#71
    'neg',#72
    'neg',#73
    'neg',#74
    'neu',#75
    'neu',#76
    'neg',#77
    'pos',#78
    'neu',#79
    'neu',#80
    'neu',#81
    'neg',#82
    'neu',#83
    'neu',#84
    'pos',#85
    'neg',#86
    'pos',#87
    'neu',#88
    'neu',#89
    'neg',#90
    'neg',#91
    'neu',#92
    'neg',#93
    'neg',#94
    'neu',#95
    'neg',#96
    'pos',#97
    'neu',#98
    'neu',#99
]

In [35]:
sent_sample_hauke['manual'] = plausibility_test
renaming = {'positive':'pos','neutral':'neu','negative':'neg'}
sent_sample_hauke['automatic'] = sent_sample_hauke[['positive', 'neutral', 'negative']].idxmax(axis=1).apply(lambda x: renaming[x])
sent_sample_hauke['match'] = sent_sample_hauke['manual'] == sent_sample_hauke['automatic']

In [36]:
sent_sample_hauke['match'].sum()

59

In [37]:
confmat_hauke = confusion_matrix(sent_sample_hauke['manual'], sent_sample_hauke['automatic'], labels=['pos', 'neu', 'neg'])
confmat_hauke

array([[ 6,  6,  3],
       [ 4, 23, 20],
       [ 1,  7, 30]])

In [38]:
old_confmat = np.array([[11, 8, 8],
                    [17, 55, 34],
                    [1, 11, 55]])

In [39]:
sent_sample_reemt_nachtrag = party_classifications_without_trump.sample(random_state=50, n=2).reset_index()
sent_sample_reemt_nachtrag.to_pickle('../data/plausibility_tests/reemt_sentiment_2.pkl')
sent_sample_reemt_nachtrag['extracted_string'].to_csv('../data/plausibility_tests/reemt_sentiment_2.csv')

In [40]:
sent_sample_reemt_ausgewertet = pd.read_csv('../data/plausibility_tests/ausgewertet/reemt_sentiment_2.csv')
sent_sample_reemt_nachtrag_ausgewertet = pd.read_csv('../data/plausibility_tests/ausgewertet/reemt_sentiment_2_nachtrag.csv')

In [41]:
sent_sample_reemt['manual'] = sent_sample_reemt_ausgewertet['Unnamed: 2']
sent_sample_reemt_nachtrag['manual'] = sent_sample_reemt_nachtrag_ausgewertet['Unnamed: 2']
sent_sample_reemt = pd.concat([sent_sample_reemt, sent_sample_reemt_nachtrag])
sent_sample_reemt.dropna(subset=['manual'], inplace=True)
renaming = {'positive':'pos','neutral':'neu','negative':'neg'}
sent_sample_reemt['automatic'] = sent_sample_reemt[['positive', 'neutral', 'negative']].idxmax(axis=1).apply(lambda x: renaming[x])
sent_sample_reemt['match'] = sent_sample_reemt['manual'] == sent_sample_reemt['automatic']

In [42]:
sent_sample_reemt['match'].sum()

51

In [43]:
confmat_reemt = confusion_matrix(sent_sample_reemt['manual'], sent_sample_reemt['automatic'], labels=['pos', 'neu', 'neg'])
confmat_reemt

array([[ 7,  3, 11],
       [ 3, 21, 13],
       [ 5, 14, 23]])

In [44]:
new_confmat = old_confmat+confmat_hauke+confmat_reemt

In [45]:
new_confmat_df = pd.DataFrame(new_confmat, index= ['pos','neu','neg'], columns=['pos','neu','neg'])
new_confmat_df.da.export_metrics()

pos       neu       neg  micro-average
accuracy                   0.825000  0.650000  0.680000       0.718333
f1                         0.406780  0.585799  0.627907       0.577500
false_discovery_rate       0.563636  0.331081  0.451777       0.422500
false_negative_rate        0.619048  0.478947  0.265306       0.422500
false_positive_rate        0.091988  0.233333  0.351779       0.211250
negative_predictive_value  0.886957  0.638889  0.807882       0.788750
positive_predictive_value  0.436364  0.668919  0.548223       0.577500
precision                  0.436364  0.668919  0.548223       0.577500
recall                     0.380952  0.521053  0.734694       0.577500
sensitivity                0.380952  0.521053  0.734694       0.577500
specificity                0.908012  0.766667  0.648221       0.788750
true_negative_rate         0.908012  0.766667  0.648221       0.788750
true_positive_rate         0.380952  0.521053  0.734694       0.577500

In [46]:
new_confmat = new_confmat.T

In [47]:
from pathlib import Path
import matplotlib as mpl
import matplotlib.font_manager as fm
import matplotlib.pyplot as plt
mpl.use('pdf')

fpath = Path(mpl.get_data_path(), "fonts/ttf/cmu_serif_roman.ttf")
fprop = fm.FontProperties(fname=fpath)

width = 6.2 #inches
height = width

font = {'family':'serif', 'serif': ['cmr10'], 'size':12}
plt.rc('font',**font)
plt.rcParams['axes.unicode_minus'] = False
plt.rc('axes', titlesize=12)
plt.rc('xtick', labelsize=12)
plt.rc('ytick', labelsize=12)

f, ax = plt.subplots(figsize=(9, 8))
f.subplots_adjust(left=0.08, bottom=.15, right=.95, top=.93)
sns.heatmap(new_confmat.T, ax=ax, fmt="3g", annot=True, linewidths=.5, cbar=False, cmap=sns.light_palette("seagreen", as_cmap=True))
ax.set_xlabel('Automatic', fontsize=12, font=fpath, color='black')
ax.set_ylabel('Manual', fontsize=12, font=fpath, color='black')
ax.set_title('Confusion Matrix of Manual Verification for german-news-sentiment-bert', fontsize=12, font=fpath, color='black')
ax.set_xticklabels(['Positive', 'Neutral', 'Negative'], size=12, font=fpath, color='black')
ax.set_yticklabels(['Positive', 'Neutral', 'Negative'], size=12, font=fpath, color='black')

f.set_size_inches(width, height*11/21)
f.savefig('../results/englisch/confusion_matrix_plausability_sentiment.pdf')

/var/folders/k5/jm1h82sn2vd8d4f_0f1091r00000gn/T/ipykernel_41014/3845287348.py:20: UserWarning: cmr10 font should ideally be used with mathtext, set axes.formatter.use_mathtext to True
  f, ax = plt.subplots(figsize=(9, 8))


In [48]:
new_confmat.sum(axis=None)

400

In [49]:
#manual
new_confmat.sum(axis=0)/400

array([0.1575, 0.475 , 0.3675])

In [50]:
#automatic
new_confmat.sum(axis=1)/400

array([0.1375, 0.37  , 0.4925])

In [51]:
afd_incorrect = 0
cdu_incorrect = 0
csu_incorrect = 0
fdp_incorrect = 2
#der eigenen inneren stimme zu folgen sven ole müller und nicole bauer beide amateur radrennfahrer aus thüringen hatten da erstmal keinen zugang
#gescheitert absolut gescheitert dann wird darüber lustig gemacht dass die fdp fordert deutsch soll im grundgesetz stehen unabhängig davon wer das
grüne_incorrect = 2
#es gibt im meldung aus der ausbremst da müssen sich die grünen besorgen musste johnny depp hingegen sei da zu sein es
#ja ich weiß es nicht also entweder einer von reifen die grünen ideen habe ich würde ich dann will ich wirklich der
linke_incorrect = 7
#auslösen wie das andreas baader verbreitet hatte man wollte und die linke szene für die für den aufstand zu zu animieren zu
#gestern hat für uns in anfangsphase brutalen betrieb gemacht über die linke seite weil immer wieder an spielbar zwar für leverkusen ganz
#geschnappt formel hingeben und mit meinem körper versucht zu schützen die linke hand nach oben gestreckt und so wir dann einige steine
#die rechte vorkammer hier die rechte hauptkammer während also hier die linke kammern wo eben die ausschluss bahnverhältnisse sich eben kaum zusammenzieht
#wurden beschädigt acht beamte leicht verletzt für heute abend hat die linke szene in leipzig neue kundgebungen angemeldet jetzt ein ganz anderes
#seit jahren ist es zur mode der scheinheiligen rechten geworden die linke als buchstäblich korrupt darzustellen wie hier in recoleta haben eine
#und ist eine riesige projektionsfläche einmal konservative die irgendwie glauben die linke sei stärker als sie eigentlich ist und weshalb habe die
spd_incorrect = 0